pipeline {
  agent any
  parameters {
    booleanParam(defaultValue: false, description: '', name: 'Selectvalue')
    string(defaultValue: "test value", description: "The required value to be selected", name: "env")
    choice(name: 'CHOICES', choices: ['one', 'two', 'three'], description: '') 
  }
  stages {
    stage ("Echo parameter value"){
      steps {
          echo "The selected value is ${params.Selectvalue}"
      } 
         }
      stage ("select the required env"){
         steps {
           echo "The selected value is ${params.env}"
      } 
         }

    stage ("Display hostname"){
      steps {
          sh "hostname"
      } 
         }
    stage ("Clean up") {
      steps {
            deleteDir()
        }
      }
      stage ("Clone Repo"){
        steps{
            sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
        }
      }
      
    }
    post {
        success {
          echo "Job successed"
        }
        failure {
          echo "Job failed"
        }
      }
  }
